version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fuelphp-app
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html/my_fuel_project
    networks:
      - fuelphp-network

  db:
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "${ATCODER_ARCHIVE_DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${ATCODER_ARCHIVE_DB_DATABASE}"
    ports:
      - "3306:3306"
    networks:
      - fuelphp-network

networks:
  fuelphp-network:
    driver: bridge
